[package]
name = "rayo-router"
description = "Rayo's radix-tree router with typed path parameters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
matchit = { workspace = true }

[lints]
workspace = true
