from collections.abc import Callable
from typing import Any

class Server:
    @property
    def port(self) -> int: ...
    @property
    def in_flight(self) -> int: ...
    def wait(self) -> None: ...
    def shutdown(self) -> None: ...

def core_version() -> str: ...
def start_server(
    host: str,
    port: int,
    routes: list[tuple[str, str, Callable[..., Any], bool, list[tuple[str, int]]]],
    loop_threads: int,
) -> Server: ...
