from collections.abc import Callable
from contextvars import Context
from types import CoroutineType
from typing import Any

class Server:
    @property
    def port(self) -> int: ...
    @property
    def in_flight(self) -> int: ...
    def wait(self) -> None: ...
    def shutdown(self, grace_seconds: float | None = None) -> None: ...

class HandlerTask:
    """The scheduler's per-request task-like; what `asyncio.current_task()`
    returns inside a Rayo handler."""

    def __call__(self, finished_future: Any = None) -> None: ...
    def cancel(self, msg: object = None) -> bool: ...
    def uncancel(self) -> int: ...
    def cancelling(self) -> int: ...
    def done(self) -> bool: ...
    def cancelled(self) -> bool: ...
    def get_loop(self) -> Any: ...
    def get_coro(self) -> CoroutineType[Any, Any, Any] | None: ...
    def get_context(self) -> Context | None: ...
    def get_name(self) -> str: ...
    def set_name(self, value: object) -> None: ...
    def result(self) -> Any: ...
    def exception(self) -> BaseException | None: ...
    def add_done_callback(
        self, callback: Callable[[HandlerTask], object], *, context: Context | None = None
    ) -> None: ...
    def remove_done_callback(self, callback: Callable[[HandlerTask], object]) -> int: ...

def core_version() -> str: ...
def start_server(
    host: str,
    port: int,
    routes: list[tuple[str, str, Callable[..., Any], bool, list[tuple[str, int]]]],
    loop_threads: int,
) -> Server: ...
